base: &base
  adapter: mongodb
  database: Wave
#These are needed to authenticate with your db
#should it run on another server
  #host: localhost
  #username: your-username
  #password: your-password

development:
  <<: *base

test:
  <<: *base
  database: Wave-test


production:
  <<: *base
